version: "3.2"
services:
  web:
    image: jonatasrenan/docker-ha-examples:ha-swarm
    ports:
      - "8000:80"
    networks:
      - front
    deploy:
      replicas: 3

networks:
  front:
    driver: overlay
